# -*- coding: utf-8 -*-
"""lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dVTjOJ6zm8e8LlUtZz6yoG-v1uw2w6SA

# Introduction to Python, Jupyter Notebooks, and GitHub
This notebook introduces Python basics and how to work in Jupyter Notebooks.

## Learning goals
- Understand the Jupyter Notebook interface (code vs. markdown cells, running cells, keyboard shortcuts).
- Write and run basic Python code (syntax, variables, data types, control flow).
- Document code using Markdown (headings, lists, LaTeX equations).
- Get a high-level overview of Git & GitHub for version control.
- Complete hands‑on challenges to reinforce each concept, including stretch problems for experienced coders.

## 1. Running Your First Python Cell
Click in the cell below and press **Shift + Enter** (or the ▶️ button) to execute it.
"""

print('Hello, world!')

"""## 2. Basic Python Syntax
Python uses **indentation** (4 spaces by convention) to define blocks.
Comments start with `#`. Anything after `#` on the same line is ignored by Python.
"""

# This is a comment
for i in range(5):
    print('Iteration', i)

"""## Activity 1 – Debug It!
The code below has three syntax/logic errors. Run it, read the traceback, then fix the errors so the loop prints
`1 3 5 7 9` on one line.
"""

# TODO: Fix the errors so this prints "0 2 4 6 8"
for i in range(10):
  if (i%2==0):
    print(i, end=" ")

"""## 3. Variables & Data Types
Python is **dynamically typed** – variable types are inferred at runtime.

| Type | Example | Literal |
|------|---------|---------|
| `int` | whole numbers | `x = 42` |
| `float` | decimal numbers | `pi = 3.14159` |
| `str` | text | `name = "Ada"` |
| `bool` | truth values | `is_valid = True` |
| `list` | ordered, mutable collection | `scores = [95, 88, 72]` |
| `dict` | key‑value pairs | `user = {'id': 1, 'name': 'Sam'}` |

Run the cell below to see the types in action.
"""

x = 42
pi = 3.14159
name = "Ada"
is_valid = True
scores = [95, 88, 72]
user = {'id': 1, 'name': 'Sam'}

print(type(x), type(pi), type(name), type(is_valid), type(scores), type(user))

"""## Activity 2 – Type Detective
1. Create two new variables:
   * `exchange_rate_usd_eur` set to `0.92` (float)
   * `countries` containing three country names of your choice (list of strings)
2. Print a sentence that says "The exchange rate for COUNTRY is X.XX." using an **f‑string** and the second country in your list.
3. Verify the data types with `type()`.
"""

# Your code here
exchange_rate_usd_eur = .92
countries = ["USA", "Canada", "Mexico"]
print(f"The exchange rate for {countries[1]} is {exchange_rate_usd_eur}.")
print(type(exchange_rate_usd_eur), type(countries))

"""## 4. Control Flow – `if`, `for`, `while`"""

number = 7
if number % 2 == 0:
    print(number, "is even")
else:
    print(number, "is odd")

"""## Activity 3 – QuackMoo
Write a loop that prints numbers 1‑25. For multiples of 4 print "Quack", for multiples of 6 print "Moo", and for multiples of both print "QuackMoo".
"""

# Your code here
for i in range(1,26):
  if i %4==0 and i%6==0:
    print("QuackMoo")
  elif i%4==0:
    print("Quack")
  elif i%6==0:
    print("Moo")
  else:
    print(i)

"""## 5. Writing Functions
Functions bundle reusable logic.
"""

def greet(name):
    """Return a friendly greeting"""
    return f"Hello, {name}!"

print(greet('Data Scientist'))

"""## Activity 4 – Factorial Function
Implement `factorial(n)` that returns the factorial of n (`factorial(0)=1`, `factorial(1)=1`, `factorial(2)=2`, etc.). Test that `factorial(5)` is 120.
"""

# Your code here
def factorial(n):
  if n==0:
    return 1
  return n*factorial(n-1)
factorial(5)

"""## 6. Importing Libraries"""

import math
import random
import numpy as np
import matplotlib.pyplot as plt

samples = np.random.randn(1000)
plt.hist(samples, bins=30)
plt.title('Histogram of Normal Samples')
plt.show()

"""## 7. Markdown Tips
Use Markdown cells to explain your work:
- `#` to `######` for headings
- `**bold**` or `*italics*`
- LaTeX math: `$E = mc^2$`

Add a Markdown cell below explaining, in your own words, what a function is and why it’s useful.
"""

# (Add a Markdown cell below instead of editing here)
# a function is a block of code, often repeated, that is written once do that it can be repeated later on through a one line call.

"""## 8. Version Control with Git & GitHub
### Why version control?
- Tracks changes to your code over time, like "Track Changes" in a document.
- Enables collaboration without overwriting each other's work.
- Provides an off‑site backup.

We will use **GitHub Classroom** occasionally to provide each student with a private repository or will walk you through steps to create a repo for an assignment.

Sign up for GitHub if you have not already (or create a new one if you would like a new account) and share it in the following Google Form: [Link](https://docs.google.com/forms/d/e/1FAIpQLSdDg85PuiLlqXGdqvoHoIwsi0IgcHkgCp8JsvI-Fkq25y4TMQ/viewform?usp=dialog)

TODO: Create a new public repository on GitHub and clone it in below:

Code:

!git clone https://github.com/example/repository.git.

## Advanced Challenge Exercises
These are optional stretch problems for students with prior coding experience.

1. **List Comprehension Speed‑Up**  
   Generate the squares of all integers from 1 to 100 000. Compare the runtime of a traditional `for` loop vs. a list comprehension using `timeit`. Plot the timing results. Further reading: https://www.geeksforgeeks.org/python/python-list-comprehension/

2. **Dictionary Comprehension Puzzle**  
   Create a dictionary that maps each lowercase letter `a‑z` to its numerical position in the alphabet **without** typing the alphabet explicitly (i.e., A is position 0, B is position 1). Further reading: https://www.geeksforgeeks.org/python/python-dictionary/

3. **NumPy Broadcasting Art**  
   Use NumPy broadcasting to create a 2‑D array that represents a grayscale image of concentric circles (hint: compute distance from the center). Display it with `plt.imshow()`.

4. **Prime Checker Function**  
   Implement `is_prime(n)` efficiently for `n ≤ 10^6`. Test it on the following primes: 2, 3, 5, 7, 9973

Choose any you like and work below.
"""

